/* Reports contain question references only, never account data or answer keys. */
(() => {
  'use strict';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const types=['Неверный ответ или проверка','Ошибка в объяснении','Не хватает изображения или текста','Неправильный порядок страниц','Другая проблема'];
  const draft=new Map();let context=null;
  const dialog=document.createElement('dialog');dialog.className='account-dialog report-dialog';dialog.id='reportDialog';dialog.setAttribute('aria-labelledby','reportTitle');
  dialog.innerHTML=`<div class="row between"><h2 id="reportTitle">Сообщить об ошибке</h2><button type="button" class="btn outline" id="reportClose" aria-label="Закрыть сообщение об ошибке">✕</button></div><p id="reportContext" class="small"></p><p id="reportTimer" class="notice" hidden>Таймер экзамена продолжает идти. Можно закрыть форму и вернуться к ней при разборе.</p><label for="reportType">Что не так?</label><select id="reportType">${types.map(t=>`<option>${t}</option>`).join('')}</select><label for="reportComment">Комментарий <span class="small">(необязательно)</span></label><textarea id="reportComment" rows="4" maxlength="800" placeholder="Например: в объяснении указан B, а проверка принимает C."></textarea><p class="small">Тема и номер добавятся автоматически. Скопируйте сообщение в чат или отправьте через GitHub. Сообщения на GitHub публичные — не указывайте личные данные.</p><div class="row"><button type="button" id="reportCopy" class="btn primary">Скопировать для чата</button><a id="reportGithub" class="btn outline" target="_blank" rel="noopener noreferrer">Открыть в GitHub ↗</a></div><p class="small">На GitHub потребуется вход и нажатие Create / «Создать». Открытие формы ещё не отправляет сообщение.</p><p id="reportStatus" role="status" class="small"></p><textarea id="reportFallback" rows="7" readonly aria-label="Готовое сообщение для копирования" hidden></textarea>`;
  document.body.append(dialog);
  const $=id=>document.getElementById(id);
  const key=()=>context.id+'|'+context.source;
  function text(){return ['Ошибка в вопросе',`Раздел: ${context.section}`,`Вопрос: ${context.source}`,`ID: ${context.id}`,`Тип: ${$('reportType').value}`,`Комментарий: ${$('reportComment').value.trim()||'Не указан'}`,`Страница тренажёра: ${location.origin+location.pathname}`,`Изображение условия: ${context.image||'Не указано'}`].join('\n');}
  function update(){if(!context)return;draft.set(key(),{type:$('reportType').value,comment:$('reportComment').value});$('reportStatus').textContent='';$('reportFallback').hidden=true;$('reportGithub').href='https://github.com/starchenkovmaksim-svg/uworldtrainer/issues/new?'+new URLSearchParams({title:'[Вопрос] '+context.source,body:text()});}
  function open(c){context={...c};const saved=draft.get(key());$('reportContext').textContent=c.source;$('reportType').value=saved?.type||types[0];$('reportComment').value=saved?.comment||'';$('reportTimer').hidden=!c.timed;update();dialog.showModal();}
  $('reportType').onchange=update;$('reportComment').oninput=update;$('reportClose').onclick=()=>dialog.close();
  $('reportCopy').onclick=async()=>{const message=text();try{await navigator.clipboard.writeText(message);$('reportStatus').textContent='Скопировано. Вставьте сообщение в чат, чтобы передать его на проверку.';}catch(_){$('reportFallback').value=message;$('reportFallback').hidden=false;$('reportFallback').focus();$('reportFallback').select();$('reportStatus').textContent='Автокопирование недоступно. Скопируйте выделенный текст вручную.';}};
  document.addEventListener('click',event=>{const button=event.target.closest('[data-report-question]');if(!button)return;const c=button.dataset.reportQuestion?JSON.parse(button.dataset.reportQuestion):window.getReportQuestion?.();if(c)open(c);});
  window.QuestionReports={button(c){return `<button type="button" class="btn outline report-trigger" data-report-question="${esc(JSON.stringify(c))}">Сообщить об ошибке</button>`;}};
})();
