const assert=require('node:assert/strict');
const {collect,session}=require('../mistake-review.js');
const q={choices:['A','B'],correct:'B',questionImages:['question.webp'],explanationImages:['explain.webp'],contextImages:['context.webp']};
const blocks=[{n:'neuro',title:'Neurology',questions:[q,q,{...q,correct:null},{...q,unavailable:true},{...q,correct:null,explanationImages:[]}]}];
const state={answers:['A','B','A','A','A'],grades:[false,true,false,false,false],submitted:[true,true,true,true,true]};
const before=JSON.stringify({blocks,state});const items=collect(blocks,()=>state);
assert.deepEqual(items.map(x=>x.id),['neuro:0','neuro:2']);
assert.equal(items[0].q.contextImages[0],'context.webp');
const a=session(items);assert.equal(a.results[0].answer,null);assert.equal(a.results[0].submitted,false);
a.submit(0);assert.equal(a.results[0].submitted,false);
a.choose(0,'X');assert.equal(a.results[0].answer,null);
a.choose(0,'B');a.submit(0);assert.equal(a.results[0].grade,true);
a.choose(0,'A');a.grade(0,false);assert.equal(a.results[0].answer,'B');assert.equal(a.results[0].grade,true);
a.grade(1,true);assert.equal(a.results[1].grade,null);
a.choose(1,'A');a.submit(1);assert.equal(a.results[1].grade,null);a.grade(1,false);
assert.deepEqual(a.totals(),{correct:1,wrong:1,pending:0,total:2});
const retry=session(items.filter((_,i)=>a.results[i].grade===false));assert.equal(retry.items.length,1);assert.equal(retry.results[0].submitted,false);
assert.equal(JSON.stringify({blocks,state}),before,'retakes never change source data or persisted first-pass state');
assert.equal(collect(blocks,()=>({grades:[]})).length,0,'another account with no grades has no errors');
console.log('PASS mistake review: filtering, fresh attempts, grading, no-key self-check, repeat, progress isolation');
